### PR TITLE
Adds saveState to this plugin

### LINKED ISSUE #4: How to save/restore the width via Ajax?
Hello!
I try to save and restore the width of each column. This is done by Ajax with a call to a Backend.
Saving seams to work for me, but I am not able to set the width of a column.
Maybe somebody can guide me? 
Thanks

### PR DESCRIPTION
**Pull request by jstark518**
Uses local storage to save the widths of rows.

Few other refactoring in the code base too.

Fixes #4

### CODE REVIEW

**Comment by jstark518** [comment]
I tried to make them as close as possible to the datatables built in state, I would suggest at least sending the datatables reference incase you need to get something from it for restoring.

**Comment by dhobi** [comment]
> I tried to make them as close as possible to the datatables built in state
Yes, sorry, forget what I said. I think that makes sense. 👍 

One last request: Could you update the readme.md as well? I'll squash merge then and release 1.7.0 🥳

**Comment by jstark518** [comment]
Made those changes

**Comment by jstark518** [comment]
> I guess you must be tired by my requests by now, I'm sorry in advance. 😅 It's about the naked array for storing the column widths which looks quite "fragile". I'm just thinking what reordering or adding/removing columns would do to an already existing and saved table. Do you think it would make sense to add some exception handling around it in case the column widths could not be restored?

(if you change the table on the client end)
- As long as you call save after adding/removing column it will update the array.

(if you change the table on the server end)
- This is a hard problem to solve, if you put the column index in the array it will have the same problem.
- Could use the text in the column header but this could also change.

But pretty much no matter what you change and if the array is incomplete datatables still figures out how to display the table without it looking bad. It really treats these widths as suggestions and will resize the table anyway.

**Comment by dhobi** [comment]
Yes, I was not thinking about solving the "server side table change case" entirely but to have some safety net in place (instead of throwing an error). This could be as simple as checking the length of the columns with the length of the saved array and refuse to restore when they do not match.

**Comment by jstark518** [comment]
> Yes, I was not thinking about solving the "server side table change case" entirely but to have some safety net in place (instead of throwing an error). This could be as simple as checking the length of the columns with the length of the saved array and refuse to restore when they do not match.

It didn't give me an error when the array size didn't match, it just did the columns it had. Simple enough fix though.

**Comment by jstark518** [comment]
@dhobi Have you had a chance to review this?

**Pull request merged**
